<?php

/*
Plugin Name: Flat 101 OGT
Plugin URI: https://www.flat101.es/
Description: This plugin will apply the word "Flat 101" before every page title. Besides, it creates an og:image meta with the featured image. Isn't cool? 
Enjoy and be happy!!
Version: 0.0.1
Author URI: https://www.flat101.es/
*/


// add text BEFORE page titles
add_filter( 'the_title', function( $title, $id ) {
	if ( 'page' == get_post_type($id) )
		return $title . ' Flat101' ;
  
	return $title;
  }, 10, 2 );

// add post featured image on header (og:image meta)
add_action('wp_head', 'meta_image');
function meta_image(){
    if( is_page() || is_single()) {
        echo '<!--Generated by Flat101 plugin--> <meta property="og:image" content="'. get_the_post_thumbnail_url(get_the_ID(),'full')   .'" />';
    }
}
  